### ISSUE TITLE
Missing documentation for  //asns endpoint (PUT and DELETE)

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4443] opened 2020-02-24 22:54 UTC
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [x] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

In this PR `https://github.com/apache/trafficcontrol/pull/4378/files`. Two new endpoints for //asns PUT and DELETE just added but lack of documentation required to test them.
## Expected / new behavior:

Add documentation for those new endpoints.

**Comment by zrhoffman** [comment] 2020-02-25 01:59
You are referring to PUT asns and DELETE asns, right? They have existed in Traffic Ops for awhile now ([PUT](https://github.com/apache/trafficcontrol/commit/cf101fce9d#diff-e1d71774f8ad89e82bd76378c68555e3R241), [DELETE](https://github.com/apache/trafficcontrol/commit/cf101fce9d#diff-e1d71774f8ad89e82bd76378c68555e3R243)).

Undocumented Traffic Ops endpoints go in #4290, in this case as a comment. I have added the two you mentioned.

**Comment by ocket8888** [comment] 2020-02-25 05:18
Duplicate of #4290

**Closed by ocket8888** 2020-02-25 05:18 UTC

**Comment by ocket8888** [comment] 2020-02-25 05:19
This is captured by the more general issue, trying to keep track of all of these in the same place seems like the best idea.

I have to close the issue with that exact text to mark it as a duplicate, or I would've explained better above :P
