### ISSUE TITLE
Traffic Router: HTTP-routed delivery service handles 'format=json' qstring incorrectly

### ISSUE THREAD

**Issue by guzzijason** [apache/trafficcontrol#3384] opened 2019-03-06 21:56 UTC
Observed in Traffic Router 2.3.1-9053

When sending query string `?format=json` in a request to a non-steering HTTP-routed DS (HTTP_LIVE_NATIONAL in this case), TR intercepts this request and does not redirect as expected. Only seems to happen with json.

Examples of correct behavior:
```
jtucke01@ARGO ~$ curl -I -X GET 'http://ccr.[REDACTED]/foo/bar'
HTTP/1.1 302 Found
Location: http://[REDACTED]/foo/bar
Content-Length: 0
Date: Wed, 06 Mar 2019 21:54:04 GMT

jtucke01@ARGO ~$ curl -I -X GET 'http://ccr.[REDACTED]/foo/bar?format=xml'
HTTP/1.1 302 Found
Location: http://[REDACTED]/foo/bar?format=xml
Content-Length: 0
Date: Wed, 06 Mar 2019 21:54:08 GMT
```
Example of unexpected behavior:
```
jtucke01@ARGO ~$ curl -I -X GET 'http://ccr.[REDACTED]/foo/bar?format=json'
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 101
Date: Wed, 06 Mar 2019 21:55:46 GMT
```

**Comment by rawlinp** [comment] 2019-03-06 21:59
Along the same lines of `?trred=false` for client_steering requests, `?format=json` will also convert the response to a 200 with the location in the response body for non-client-steering requests. My guess is we can't really change that behavior because it might break clients that depend on that.

**Comment by mitchell852** [comment] 2019-03-06 22:13
@guzzijason - what do you think the severity is? critical, major, medium, minor?

**Comment by elsloo** [comment] 2019-03-07 00:24
This is not a bug and is something that has existed in Traffic Router for some time. Closing this issue for now. If you would like to see this behavior changed, please post to the dev or general list and ask if others are currently relying on the behavior and we can evaluate the change based on that discussion.

**Closed by elsloo** 2019-03-07 00:24 UTC
Labels: Traffic Router, bug
