### ISSUE TITLE
Limit Tenant Access by CDN

### ISSUE THREAD

**Issue by ryandurfey** [apache/trafficcontrol#1564] opened 2017-11-17 15:13 UTC
Allow CDNs to be assigned to tenants which would allow/prevent service creation on certain CDNs.

We may want to isolate tenants to creating services on certain CDNs.

**Comment by mitchell852** [comment] 2017-12-18 20:46
Can this be closed? Looks like a duplicate of #1669

**Comment by ashish-timilsina** [comment] 2018-02-01 19:54
@ryandurfey 
@ashish-timilsina

**Closed** 2018-07-20 21:14 UTC
Labels: enhancement
