### ISSUE TITLE
Delivery Services can be assigned servers from a different CDN

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#4116] opened 2019-11-14 22:34 UTC
## I'm submitting a ...
- bug report

## Traffic Control components affected ...
- Traffic Ops

## Current behavior:
Similar to #3756 , the TO API allows servers to be assigned to Delivery Services outside of their respective CDNs via the endpoints:

- `deliveryservices/{{xml_id}}/servers`
- `deliveryserviceserver`

(and also `/servers/{{ID}}/deliveryservices` at the time of this writing, but that's fixed by #3761)

## Expected / new behavior:
Servers outside of a Delivery Service's CDN should not be assignable to said Delivery Service.

## Minimal reproduction of the problem with instructions:
1. Create a (Edge-tier cache or Origin) Server in CDN A
1. Create a Delivery Service in CDN B
1. Try to assign the Server to the Delivery Service
1. Notice how that worked even though it shouldn't.

**Comment by mitchell852** [comment] 2019-11-15 16:48
just for the record, TP prevents this. When assigning DS's to a Server, only DS's in the same cdn are  displayed.

**Comment by lbathina** [comment] 2019-11-15 17:17
this is exactly duplicate of https://github.com/apache/trafficcontrol/issues/4085 which is closed saying its duplicate of https://github.com/apache/trafficcontrol/issues/3756 - it is not. they are two different scenarios. It shouldn't have been closed in first place.

**Comment by mitchell852** [comment] 2019-11-20 16:15
along the same lines, you can do the following:

1. assign an edge server in cdn 1 to a ds in cdn 1 (which is fine and expected)
2. update the edge server to be in cdn 2

now you have an edge cache from cdn 2 assigned to a ds in cdn 1.

i guess on server update, if changing the cdn value, the update should be rejected if the server is assigned to any ds's?

**Comment by rob05c** [comment] 2019-11-20 16:38
>i guess on server update, if changing the cdn value, the update should be rejected if the server is assigned to any ds's?
+1

**Closed** 2020-05-26 15:57 UTC
Labels: Traffic Ops, bug, major
