### ISSUE TITLE
Delivery service request can be assigned to a user of different tenancy

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4168] opened 2019-12-05 17:27 UTC
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

A `PUT` request to `deliveryservice_requests/{{id}}/assign` can be assigned to a user with different tenancy than the user which originally created the request.
Where Request Body contains:
```
{
    "assigneeId": {{id}}
}
```
And the `assigneeId` is the Id of a user with different tenancy than the creator of the delivery service request.
Returns:
```
HTTP/1.1 200 OK
{
    "alerts": [
        {
            "text": "deliveryservice_request was updated.",
            "level": "success"
        }
    ],
   "response": {
          .
          .
          .
   "status": "submitted"
   }
}
```
## Expected / new behavior:

Should not be able to assign to a user with a different tenancy.
## Anything else:

According to the documentation here: https://traffic-control-cdn.readthedocs.io/en/latest/admin/quick_howto/ds_requests.html
*Assignment is currently limited to current user. This is optional as fulfillment will auto-assign the request to the user doing the fulfillment.* 
Which works on Traffic Portal, but the API allows for ANY user to be assigned.

**Comment by mitchell852** [comment] 2019-12-06 17:28
A DSR wraps a DS. That DS has a tenant. Let's imagine the following tenant tree:

- root
-- tenant 1
--- tenant 1.1
-- tenant 2
--- tenant 2.2

If the DSR is for DS A and DS A belongs to tenant 1.1, then the DSR can be only be assigned to users that belong to tenant 1.1 or higher (tenant 1 and root). 

This bug allows the DSR to be assigned to tenant 2 or tenant 2.2.

This is problematic because you can assign DSRs to users and they won't be able to see that DSR due to tenancy.

**Comment by mitchell852** [comment] 2020-08-04 16:52
Duplicate of #4167

**Closed by mitchell852** 2020-08-04 16:52 UTC
Labels: Traffic Ops, bug
