### ISSUE TITLE
Traffic Monitor still starting, some caches unpolled

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#2251] opened 2018-05-10 12:56 UTC
I have an edge cache that's currently being built. I restarted Traffic Monitor and after 10 minutes it still haven't started.

Version: traffic_monitor-2.2.0-7731.6ea85056.el7.x86_64

Not sure if this is by design or a bug, but different behavior than the java version.

```
ERROR: datareq.go:261: 2018-05-10T12:52:12.739231563Z: Request Error: /publish/CrStates: service still starting, some caches unpolled: map[cdn1cdedge0001:{}]
ERROR: datareq.go:261: 2018-05-10T12:52:13.709375974Z: Request Error: /publish/CrStates: service still starting, some caches unpolled: map[cdn1cdedge0001:{}]
ERROR: datareq.go:261: 2018-05-10T12:52:13.711937723Z: Request Error: /publish/CrStates: service still starting, some caches unpolled: map[cdn1cdedge0001:{}]
ERROR: datareq.go:261: 2018-05-10T12:52:14.115835758Z: Request Error: /api/bandwidth-capacity-kbps: service still starting, some caches unpolled: map[cdn1cdedge0001:{}]
ERROR: datareq.go:261: 2018-05-10T12:52:14.206949351Z: Request Error: /api/bandwidth-kbps: service still starting, some caches unpolled: map[cdn1cdedge0001:{}]
ERROR: asm_amd64.s:2197: 2018-05-10T12:52:14.280999564Z: monitor config server cdn1cdedge0001 profile EDGE_VM_713 has no polling URL; can't poll
ERROR: datareq.go:261: 2018-05-10T12:52:14.375944312Z: Request Error: /publish/EventLog: service still starting, some caches unpolled: map[cdn1cdedge0001:{}]
ERROR: datareq.go:261: 2018-05-10T12:52:14.403802012Z: Request Error: /publish/CrStates: service still starting, some caches unpolled: map[cdn1cdedge0001:{}]
```

**Comment by smalenfant** [comment] 2018-05-10 12:59
I think part of the problem is that a CR-Config was not executed after changing the profile. cdn1cdedge0001 profile in Traffic Ops and CR-Config isn't matching. But I believe this should not prevent traffic monitor from starting.

**Comment by mitchell852** [comment] 2018-07-20 20:13
i'm going close this as a duplicate of #1738

**Closed by mitchell852** 2018-07-20 20:13 UTC
Labels: Traffic Monitor, intake, major
