### ISSUE TITLE
Add Traffic Ops Client Functions for all nullable objects and ReqInf

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3345] opened 2019-02-20 15:55 UTC
Many TO Client objects are missing Nullable objects, and missing returning ReqInf.

We need to go through and add all of these, and mark functions missing either as `// Deprecated`.

Nullable objects are necessary to distinguish missing from empty values, and `ReqInf` is necessary for clients to get the IP (which is important to users, if there's an error or unexpected behavior, and TO is behind a GSLB).

**Comment by rawlinp** [comment] 2021-06-03 15:54
Duplicate of #2546

**Closed by rawlinp** 2021-06-03 15:54 UTC
Labels: TO Client (Go), Traffic Ops, tech debt
