### ISSUE TITLE
RFE: API route to query servercheck data by host name or ID

### ISSUE THREAD

**Issue by guzzijason** [apache/trafficcontrol#3577] opened 2019-05-15 15:18 UTC
Currently, this route is used to GET servercheck data:
```
/api/$version/servers/checks
```
This returns data for all servers. In order to better integrate with monitoring/alerting systems, I would like to have the option to request the same data for a specific host only, either by name or ID. Right now, its workable, but each individual monitoring check that uses this data would need to retrieve the large chunk of data and parse out the specific host the check cares about.

**Comment by rimashah25** [comment] 2021-02-02 16:58
I can take this one since it is a duplicate of https://github.com/apache/trafficcontrol/issues/5463

**Closed** 2021-02-26 17:35 UTC
Labels: Traffic Ops, enhancement
