### ISSUE TITLE
TrafficRouter in HTTP requires an SSL cert before pulling config data from TrafficOps

### ISSUE THREAD

**Issue by villajo** [apache/trafficcontrol#2625] opened 2018-08-03 16:21 UTC
Issue can be replicated by.. 

1.) Creating a new CDN in Traffic Portal that's set for HTTP protocol (Not HTTPS). DO NOT create an SSL key for it. 
2.) Building and configuring Traffic Router and Traffic Monitor per instructions on TrafficControl. 
3.) Make sure that Traffic Monitor is working properly. Once that's working, move on to Traffic Router. 
4.) You'll notice that Traffic Router will continue to attempt to get SSL keys, steering, geo data even if that data should be available without https. 
5.) Perform a CRSnap. Notice how nothing has changed in the logs. 
6.) Create an SSL key for the CDN. Perform a CRSnap afterwards. 
7.) You'll see that the TR starts finding the data it should have had without an SSL key.

**Comment by mitchell852** [comment] 2020-12-08 17:01
@rawlinp - do u know if creating an HTTPS delivery service w/o certs causes TR some issues anymore? If so, maybe we need to add a Major label to this.

**Comment by rawlinp** [comment] 2020-12-08 17:07
That is a different issue than this issue, and that is actually by design I believe. If you have an HTTPS DS w/o a cert, TR will continue to poll TO for the missing cert until it gets one.

_This_ issue might actually be fixed, since there were a lot of cert-related enhancements completed since 2 years ago. I can try to verify this.

**Comment by rawlinp** [comment] 2020-12-09 17:18
This issue appears to be fixed now that TR generates a `default.invalid` cert. I was able to curl a DS on a new CDN that didn't have any SSL keys generated yet.

**Closed by rawlinp** 2020-12-09 17:18 UTC
Labels: Traffic Ops, Traffic Portal, bug
