### ISSUE TITLE
[TC-71] Remove hardcoded reference to ccr in UI/DeliveryService.pm

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1025] opened 2017-08-29 12:48 UTC
<p>because the value of http.routing.name in applicationContext.xml can be anything (defaults to tr), this needs to be dynamic rather than referencing the hard-coded value of 'ccr'. So my suggestion would be:</p>

<p>create a global parameter using a database migration file and name the parameter http.routing.name and set the default value to 'tr'. then in the code, fetch the value of http.routing.name and use that on line 147 &amp; 150</p>

<p><a href="https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/UI/DeliveryService.pm#L147" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/UI/DeliveryService.pm#L147</a></p>

<p><a href="https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/UI/DeliveryService.pm#L150" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/UI/DeliveryService.pm#L150</a></p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-71">https://issues.apache.org/jira/browse/TC-71</a>

**Comment by mitchell852** [comment] 2017-08-29 21:36
@rawlinp should have covered this in his PR

**Comment by rawlinp** [comment] 2017-08-29 21:41
Yes, this looks like a duplicate of https://issues.apache.org/jira/browse/TC-287 which will be addressed by #865.

**Closed** 2020-08-04 15:55 UTC
Labels: Traffic Ops, Traffic Router, enhancement, minor
