### ISSUE TITLE
Internal Server Error when create ANY_MAP Delivery Service

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4553] opened 2020-03-27 16:26 UTC
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Create an ANY_MAP delivery service. Choose Fullfill Request Immediately. It will not create new Delivery Service and return Internal Server Error.
## Expected / new behavior:

Let user create new Delivery Service and return different message.

**Comment by ocket8888** [comment] 2020-03-27 16:32
So any other type of Delivery Service can be created successfully?

**Comment by mhoppa** [comment] 2020-03-27 16:34
it does look like the error for the any_map is related if you chose a CDN that is dnssecenabled that doesnt have keys created it will error with 500 and log:

```
ERROR: api.go:180: 2020-03-27T16:29:32.990780963Z: 96.118.18.17:54722 creating DNSSEC keys: getting DNSSec keys from Riak: no DNSSec keys found
```

**Comment by dpham692** [comment] 2020-03-27 16:35
Yeah, I chose different CDN and Delivery Service created successfully.

**Comment by mhoppa** [comment] 2020-03-31 20:43
dup of https://github.com/apache/trafficcontrol/issues/4451 btw

**Comment by ocket8888** [comment] 2020-03-31 20:50
Close it, then?

**Comment by mhoppa** [comment] 2020-03-31 20:55
yes please

**Comment by ocket8888** [comment] 2020-03-31 21:32
Duplicate of #4451

**Closed by ocket8888** 2020-03-31 21:32 UTC
Labels: bug
