### ISSUE TITLE
Traffic Ops Does Not Update DNSSEC Keys on Delivery Service Update

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#2805] opened 2018-09-11 17:27 UTC
Traffic Ops Does Not Update DNSSEC Keys on Delivery Service Update.

As far as I can tell, this has been a bug forever. The old Perl endpoint doesn't update them either, and it appears it never has.

This means updating anything in a DS which changes the served FQDNs (e.g. Routing Name, Regexes) will break DNSSEC.

**Comment by mitchell852** [comment] 2018-10-29 14:07
CDN-2708

**Comment by mattjackson220** [comment] 2020-10-08 21:42
reopening because only partially fixed in #5083

**Comment by mitchell852** [comment] 2020-12-08 21:05
So looks like between #5083 and #5297 you can no longer change anything DS-related that DNSSEC depends on therefore, i believe this issue can be closed as reproducing it is no longer possible but I'll defer to the issue creator @rob05c

**Comment by rawlinp** [comment] 2021-01-25 17:52
Yes, I believe this can be closed out now with the completion of #5297. If you can't change the HOST_REGEXP set number 0, then you can't change the deliveryservice zone name, which is what would necessitate new DNSSEC keys for that deliveryservice.

**Closed by rawlinp** 2021-01-25 17:52 UTC
Labels: Traffic Ops, bug, major
