### ISSUE TITLE
[TC-214] SSL Customer Cert Upload

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#949] opened 2017-08-29 12:43 UTC
<p>Allow CDN tenants to upload a custom cert to the CDN for application to their services.</p>

<p>Customers that split traffic across multiple CDNs have to use their own FQDN and SSL cert. We need a process for them to securely upload their certs to us for storage and application against their services.</p>

<p>We also need to capture the FQDN of the cert and make sure it is applied as a host regex for their service so that the CDN recognizes it. It's possible that it is already in place when they upload the cert, but this should be checked.</p>

Author: Ashish Timilsina
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-214">https://issues.apache.org/jira/browse/TC-214</a>

**Comment by ashish-timilsina** [comment] 2018-02-01 20:02
@ryandurfey 
@ashish-timilsina

**Comment by mitchell852** [comment] 2019-10-14 20:16
duplicate of #1905

**Closed by mitchell852** 2019-10-14 20:16 UTC
Labels: SSL, Traffic Ops, enhancement, major, self_service
