### ISSUE TITLE
Disallow underscore in xmlId

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#3312] opened 2019-02-08 05:59 UTC
The XMLID by default is part of the delivery service example URLs/regex.  We should add a constraint to disallow any characters forbidden in URLs such as `_`.  TrafficOps currently allows you do do this, but you will get back a 400 error back from TR whenever you use the example url generated by default.  Tangentially, this also helps #3267.

**Comment by ocket8888** [comment] 2019-02-08 17:45
To be maybe a bit more exhaustive, the TO API considers `aB&%=/#@$^*()[]!{}+\\|`~` to be a perfectly valid xml_id, and (I think) only the `a` ought to be allowed. Maybe `B` if we implement casefolding for SNI quirks in SSL implementations. Additionally, the TP validator catches none of that either, and will also let you submit a form with a `.` in it (though that fails because the API rejects it) but I do believe checks for `_`

**Comment by jhg03a** [comment] 2019-02-08 18:56
I ran into this using the TO API directly rather than TP.

If the XMLID is going to be a separate concept than what goes into the default host regex, we should fail to make a default regex as painful as that is and alert the user.  There's a high likelyhood the user would be just fine with an XMLID that is compliant with a more conservative validation pattern in my opinion.

**Comment by mitchell852** [comment] 2019-02-14 19:56
https://github.com/apache/trafficcontrol/blob/master/traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html#L101

TP only checks that you don't have spaces in the xml id

`ng-pattern="/^\S*$/"`

a. it's great if the API is doing a tighter validation
b. i think it's fine to duplicate that validation in TP but seems like a lower priority as the api does it anyhow.

**Comment by ocket8888** [comment] 2019-02-14 20:38
No, you're right, that would be an enhancement to TP. It's a bug in TO.

And maybe this is a totally separate conversation, but what are we doing with `ng-pattern` that can't be done with [`pattern`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#pattern)?

**Comment by jhg03a** [comment] 2019-02-15 01:55
I'm not using TP and this happened.  It needs to be enforced in TO and/or Postgres.

**Comment by ZugNZwang** [comment] 2019-11-14 18:53
When making a `POST` request to `https://{{TO_BASE_URL}}/api/{{api_version}}/deliveryservices` with an `xmlId` key containing any of these:

- special character
- underscore 
- capital letters
- beginning/ending hyphens

it is allowed on the TO API. The TO API only handles spaces and periods.
Traffic Portal does not allow for any of these.
Documentation of xmlId found here: https://traffic-control-cdn.readthedocs.io/en/latest/overview/delivery_services.html#xml-id

**Comment by rob05c** [comment] 2019-11-14 21:10
We should also disallow characters not allowed in POSIX filenames (possibly also Windows filenames). Because Cache Configs put the xml_id in some config file names, e.g. `hdr_rw_dsname.config`

**Comment by ocket8888** [comment] 2019-11-14 22:43
That's a good point but I'm not sure that the definition of a DNS label actually has any overlap with forbidden characters in filenames.

**Comment by mitchell852** [comment] 2021-03-16 16:58
![image](https://user-images.githubusercontent.com/251272/111349086-72fdcb00-8646-11eb-9900-c6261ac6d25c.png)

^^ TP does not allow it but TO API will

**Comment by ocket8888** [comment] 2021-03-25 15:28
Duplicate of #5658

**Closed by ocket8888** 2021-03-25 15:28 UTC
Labels: Traffic Ops, Traffic Portal, improvement, medium
