### ISSUE TITLE
deliveryserviceserver POST endpoint can add servers with mismatching CDN from Delivery Service

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4085] opened 2019-11-05 22:02 UTC
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

A `POST` request to `/#!/deliveryserviceserver` with a server that belongs to a different CDN than the CDN associated to the delivery service is allowed, returns status code `200 OK`
## Expected / new behavior:

Should not be allowed to add server with mismatching CDN
Should return status code `400 Bad Request`
## Anything else:

Server could also be of any Type and be added, does not have to be an `EDGE` or `ORG`.
Traffic Portal handles this by calling the `deliveryservices/{{ID}}/servers/eligible` endpoint in order to populate the dropdown list of servers the user can add.

**Comment by ocket8888** [comment] 2019-11-05 23:25
Duplicate of #3756

**Closed by ocket8888** 2019-11-05 23:25 UTC
