### ISSUE TITLE
trying to delete a ds that has an open ds request is successful

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#2595] opened 2018-07-27 15:45 UTC
With ds requests turned on in traffic_portal_properties.json, all changes to a ds (create, update or delete) result in the creation of a ds request.

however, if you are an admin, you can select "fulfill immediately" for the ds request. this will result in:

1. creating a ds request to delete the ds and immediately marking it as complete
2. deleting the ds

#1 should fail if an existing ds request is open (status != complete) for the ds which it does but #2 still succeeds (which it should not).

UPDATE:
@dsouza93 found this issue as well (#3717), the underlying issue sounds the same:

When there is an open delivery service request for a delivery service, and a user attempts to change a value on the delivery service and "fulfill immediately", Traffic Portal displays an error that there is an active delivery service request open for said delivery service. The delivery service data is then updated anyway. I am not sure if this is intended behavior and is to serve as a warning or if it supposed to prevent updates, but thought I'd bring it up.

My specific use case was when there was a delivery service request in the "pending" status with the only action left was to "complete" the request. I then set the delivery service itself to "active"/"fulfill immediately" without completing the delivery service request.

I am unsure if this will occur when other fields are altered or if it will occur when DS requests are in other states.

**Comment by anna-k-1** [comment] 2018-10-29 20:48
CDN-3157

**Comment by jhg03a** [comment] 2019-07-16 00:08
This also sounds like a duplicate of #3512

**Closed** 2019-07-24 14:28 UTC
Labels: Traffic Portal, bug
