### ISSUE TITLE
Requests to cache_stats endpoint returns Internal Server Error

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4045] opened 2019-10-30 17:15 UTC
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [X] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Requests to `https://{{TO_BASE_URL}}/api/{{api_version}}/cache_stats?cdnName=ALL&endDate=2019-10-28T20:49:00Z&metricType=bandwidth&startDate=2019-10-28T20:45:00Z` returns 500 internal server error
## Expected / new behavior:

Response code should be 200 with valid response structure.

**Comment by lbathina** [comment] 2019-10-30 17:25
not a duplicate but I believe the fix for both is same!

**Comment by ZugNZwang** [comment] 2019-10-30 17:47
Problem still manifests after waiting 5 minutes.

**Comment by ocket8888** [comment] 2019-10-30 17:51
Okay, likely that this is a duplicate of #4021 - can you show us the error in the TO logs? It'll make it easier to track down.

**Comment by lbathina** [comment] 2019-10-30 18:44
this issue happens when there is no data to return.

**Comment by ocket8888** [comment] 2019-10-30 18:46
What is/are the exact line/lines that tells/tell you that?

**Comment by lbathina** [comment] 2019-10-30 18:52
```
ERROR: api.go:136: 2019-10-30T18:25:17.695385277Z: 96.118.19.98:60278 Getting summary response from Influx: Improper number of series: 0
ERROR: api.go:136: 2019-10-30T18:25:17.75008225Z: 96.118.19.98:60280 Getting summary response from Influx: Improper number of series: 0
```
Also, request on a CDN that has value we did not get error.

**Comment by mhoppa** [comment] 2019-10-30 20:42
@ocket8888 since we are rewriting the Perl implementations I think we keep the same behavior when there is no data and return 200 with no data. Are you okay with that ?

**Comment by ocket8888** [comment] 2019-10-30 20:50
That sounds fine to me. Influx giving back no data doesn't necessarily mean it's encountering problems, just that maybe it doesn't have any data.

**Comment by mhoppa** [comment] 2019-10-30 20:51
sounds good Ill make the change to deliveryservice_stats as well

**Closed** 2019-10-30 23:03 UTC
Labels: Traffic Ops, Traffic Stats, bug, minor
