### ISSUE TITLE
Upgrade Postgres to newer version

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#3709] opened 2019-07-01 22:09 UTC
Postgres 9.6 will be end of life in November of 2021.  While that is still a while away, we should start thinking now about our upgrade plans.  As of today 12.x is the most recent version of Postgres, however we should consider upgrading to the latest version whenever we do decide the time is right.

https://www.postgresql.org/support/versioning/

**Comment by jhg03a** [comment] 2019-07-01 22:32
Duplicate of #3362

**Closed by jhg03a** 2019-07-01 22:32 UTC
Labels: Traffic Ops
