### ISSUE TITLE
TP do not return error message on current page when DELETE Server Capabilities 

### ISSUE THREAD

**Issue by dandypham** [apache/trafficcontrol#4076] opened 2019-11-04 18:32 UTC
## I'm submitting a ...
- bug report

## Traffic Control components affected ...
- Traffic Portal

## Current behavior:
When deleting server capabilities that are required by Delivery Services the user will see no error until he or she is redirected to `/#!/server-capabilities`.

## Expected / new behavior:
Display the error message right on that page. Specifically, on the `/#!/server-capabilities/{{capabilitiesname}} ` page.

## Minimal reproduction of the problem with instructions:
1. Add 1 Require Server Capabilities on any Delivery Service by clicking on <kbd>More</kbd>&rarr;<kbd>Manage Required Server Capabilities</kbd>
2. Now try to DELETE the Server Capabilities just use by clicking on <kbd>Configure</kbd>&rarr;<kbd>Server Capabilities</kbd> and then the <kbd>Delete</kbd> button (and confirming deletion).
3. Notice that the resulting error message will not display on `/#!/server-capabilities/{{capabilitiesname}}` page right away but have to back to the `/#!/server-capabilities` to see it.

**Comment by mhoppa** [comment] 2019-11-04 18:44
This was just fixed on Master - https://github.com/apache/trafficcontrol/pull/4073.

Please ensure your environment has latest code

**Comment by lbathina** [comment] 2019-11-05 23:46
validated and the issue is fixed. can be closed.

**Closed** 2019-11-05 23:51 UTC
Labels: Traffic Portal, bug, minor
