### ISSUE TITLE
deliveryservice_requests/id/assign returns Internal Server Error when id doesn't exist

### ISSUE THREAD

**Issue by ericholguin** [apache/trafficcontrol#4170] opened 2019-12-05 19:43 UTC
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

`PUT` request to `deliveryservice_requests/{{id}}/assign` where the delivery service request id doesn't exist returns:
```
HTTP/1.1 500 Internal Server Error
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```

**Comment by heneriknguyen** [comment] 2023-07-18 22:56
This issue was closed in: https://github.com/apache/trafficcontrol/pull/7099

**Comment by heneriknguyen** [comment] 2023-07-18 23:01
For a non-existing DSR [e.g. id=1], the assignment works correctly with the following alert: 
`
HTTP/1.1 404 Not Found
{
	"alerts": [{
		"text": "no such Delivery Service Request: 1",
		"level": "error"
	}]
}
`

**Comment by rimashah25** [comment] 2023-07-18 23:02
Based on above comment and I tested it too, I confirm the issue is fixed.

**Closed by rimashah25** 2023-07-18 23:02 UTC
Labels: bug, Traffic Ops, low impact, good first issue, hacktoberfest
