### ISSUE TITLE
Reserved consistentHashQueryParameters cause internal server error

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#6385] opened 2021-11-25 20:33 UTC
## This Bug Report affects these Traffic Control components:
- Traffic Ops

## Current behavior:
Trying to update or create a Delivery Service to use a reserved query string parameter name like "trred" or "format" causes a 500 Internal Server Error response.

## Expected behavior:
I'm almost certain the old behavior was more proper; the API should return a client-level error and accompanying Alert that tells the user they can't do what they're trying to do.

## Steps to reproduce:
```console
$ topost -kp deliveryservices '{
	"active": false,
	"cdnId": 2,
	"displayName": "test",
	"dnsBypassCname": "test",
	"dscp": 1,
	"geoLimit": 1,
	"geoLimitCountries": "[US, CA]",
	"geoProvider": -7,
	"initialDispersion": 1,
	"ipv6RoutingEnabled": true,
	"logsEnabled": true,
	"missLat": 0,
	"missLong": 0,
	"multiSiteOrigin": false,
	"orgServerFqdn": "http://origin.infra.ciab.test",
	"protocol": 7,
	"qstringIgnore": 5,
	"rangeRequestHandling": 0,
	"regionalGeoBlocking": false,
	"tenantId": 1,
	"typeId": 1,
	"xmlId": "test",
	"consistentHashQueryParams": ["format", "something fine", "trred"]
}'
```

**Comment by asheikm** [comment] 2021-12-14 10:43
Hi 
Can this bug reproduced using cdn-in-box ?

**Comment by asheikm** [comment] 2021-12-14 17:45
ok, I tried to build it with docker-compose 1.25.4 but the compose version 3.8 in YAML files only supported from version 1.25.5 https://github.com/docker/compose/releases/tag/1.25.5. adding it here on the hope it helps someone.

Also i am getting this error,
Step 10/35 : FROM common-traffic-server-dependencies AS common-cache-config-layers
 ---> f76f2258a217
Step 11/35 : COPY infrastructure/cdn-in-a-box/cache/trafficserver.rpm /trafficserver.rpm
COPY failed: file not found in build context or excluded by .dockerignore: stat infrastructure/cdn-in-a-box/cache/trafficserver.rpm: file does not exist
ERROR: Service 'edge' failed to build : Build failed

**Comment by zrhoffman** [comment] 2021-12-14 18:51
> ok, I tried to build it with docker-compose 1.25.4 but the compose version 3.8 in YAML files only supported from version 1.25.5 https://github.com/docker/compose/releases/tag/1.25.5. adding it here on the hope it helps someone.

The Python version of docker-compose (versions < v2.0.0) is no longer supported. They rewrote docker-compose in Go.

> Also i am getting this error, Step 10/35 : FROM common-traffic-server-dependencies AS common-cache-config-layers ---> f76f2258a217 Step 11/35 : COPY infrastructure/cdn-in-a-box/cache/trafficserver.rpm /trafficserver.rpm COPY failed: file not found in build context or excluded by .dockerignore: stat infrastructure/cdn-in-a-box/cache/trafficserver.rpm: file does not exist ERROR: Service 'edge' failed to build : Build failed
> 
> The RPM file is not found in given path infrastructure/cdn-in-a-box/cache/trafficserver.rpm. Should it be built separately?

All of the RPMs necessary to run CDN in a Box will be built and placed in the correct locations if you just run make` from the `infrastructure/cdn-in-a-box` directory. From the [documentation](https://traffic-control-cdn.readthedocs.io/en/latest/admin/quick_howto/ciab.html#building):

https://github.com/apache/trafficcontrol/blob/e67c967a8b73bdddf75851d66c051694b20373a9/docs/source/admin/quick_howto/ciab.rst#L41

**Comment by asheikm** [comment] 2021-12-15 05:28
Ok, Thanks , It is building now, stragely, make takes lot of time, I am on VM OL8, which is taken as CentOS 8, thats fine anyway. It is still building

**Comment by ocket8888** [comment] 2021-12-15 06:33
`make` builds sequentially. I think about 80% of its time is spent on building the builder image for the ATS RPM (citation needed). `make -j` is marginally faster. When building on systems that use `rpm` to manage packages (which is LSB-compliant, to be fair) can build quite a bit faster with `make native`. The absolute fastest is `make -j native`, where supported. But at any rate, building once will expedite future builds.

**Comment by asheikm** [comment] 2021-12-15 10:16
ok, I got it, now the cdn-in-a-box is running fine.

**Comment by zrhoffman** [comment] 2021-12-15 16:50
> `make` builds sequentially. I think about 80% of its time is spent on building the builder image for the ATS RPM (citation needed). `make -j` is marginally faster. When building on systems that use `rpm` to manage packages (which is LSB-compliant, to be fair) can build quite a bit faster with `make native`. The absolute fastest is `make -j native`, where supported. But at any rate, building once will expedite future builds.

`make native` is temporarily broken due to #6419

**Comment by asheikm** [comment] 2021-12-15 20:35
> > `make` builds sequentially. I think about 80% of its time is spent on building the builder image for the ATS RPM (citation needed). `make -j` is marginally faster. When building on systems that use `rpm` to manage packages (which is LSB-compliant, to be fair) can build quite a bit faster with `make native`. The absolute fastest is `make -j native`, where supported. But at any rate, building once will expedite future builds.
> 
> `make native` is temporarily broken due to #6419

Fix merged with master now https://github.com/apache/trafficcontrol/pull/6420

**Comment by asheikm** [comment] 2021-12-16 03:06
can we directly issue this command on cli ? or with curl ? 
```
$ topost -kp deliveryservices '{
	"active": false,
	"cdnId": 2,
	"displayName": "test",
	"dnsBypassCname": "test",
	"dscp": 1,
	"geoLimit": 1,
	"geoLimitCountries": "[US, CA]",
	"geoProvider": -7,
	"initialDispersion": 1,
	"ipv6RoutingEnabled": true,
	"logsEnabled": true,
	"missLat": 0,
	"missLong": 0,
	"multiSiteOrigin": false,
	"orgServerFqdn": "http://origin.infra.ciab.test",
	"protocol": 7,
	"qstringIgnore": 5,
	"rangeRequestHandling": 0,
	"regionalGeoBlocking": false,
	"tenantId": 1,
	"typeId": 1,
	"xmlId": "test",
	"consistentHashQueryParams": ["format", "something fine", "trred"]
}'
```

**Comment by ocket8888** [comment] 2021-12-16 06:18
`topost` is a utility provided by the Python client for Traffic Ops. It has an unofficial hosting on PyPI: https://pypi.org/project/Apache-TrafficControl/

**Closed** 2023-04-05 21:18 UTC
Labels: Traffic Ops, low impact, regression bug, low difficulty
