### ISSUE TITLE
Parent.Config generats incorrect parent when DS share same origin

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4098] opened 2019-11-07 23:02 UTC
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Clone and existing DS 
Add capabilities to it
Have a edge with same capabilities+  assigned to ds
Make sure there are no edges available for that capability. 
check parent.config
should have parent in parent.config to be blank 
Queue server updates
curl -Lvs  <http://fqdn/assert.m3u8>
check via header 
should have only edge listed. 

## Expected / new behavior:

has mid on the parent.config and via header.

## Anything else:

also seems its an existing issue https://github.com/apache/trafficcontrol/issues/3537 
would nullify the very purpose of have capabilities added.

**Comment by rob05c** [comment] 2019-11-08 16:50
Duplicate of #3537

> would nullify the very purpose of have capabilities added.

Well, if you have Duplicates, the config will be wrong. This is a known issue. It's a fundamental limitation of ATS, not something we can fix in TC. All we can do is give users a warning when they try to do it.

We could theoretically prevent it in TC, but we have known users who require the ability to have multiple DSes with the same Origin (e.g. AWS).

I don't think this is a reason not to do Server Capabilities, and again, there's not really anything we can do about it, besides giving users a warning.

**Closed by rob05c** 2019-11-08 16:50 UTC

**Comment by mitchell852** [comment] 2019-11-13 22:08
@ocket8888 - want to add this additional problem scenario to the description in #3537
