### ISSUE TITLE
TP changing Signing Algorithm to "None" does not work

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#2854] opened 2018-09-20 22:50 UTC
In Traffic Portal,  I have a DeliveryService with Signing Algorithm set to "URL Signing Keys".   If I switch this to "None" and Update,  then look at that field again, it still is "URL Signing Keys".

Using the API,  if I change that field to `null` and `signed` to `false`,  a PUT properly changes it to `nil` and `false` in the database.   If I leave `signed` as `true` and set `signingAlgorithm` to `null`,  the result is `signed`: `true` and `signingAlgorithm`: `url_sig`.

TP and the TO API need to handle this better..

**Comment by rivasj** [comment] 2018-09-21 19:58
Duplicate of https://github.com/apache/trafficcontrol/issues/2836 . I'm currently working this issue

**Comment by rivasj** [comment] 2018-09-25 19:37
Closed by #2859

**Closed** 2018-10-16 19:35 UTC
Labels: Traffic Ops API (golang), Traffic Portal, bug
