### ISSUE TITLE
[TC-215] SSL Automate Standard Cert Generation and Application

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#973] opened 2017-08-29 12:44 UTC
<p>It currently takes 2-3 business days to generate and apply an SSL cert. This is a manual process for several departments which means it often gets slowed down due to hand offs. We would like to automate the SSL cert generation and application process.</p>

Author: Ashish Timilsina
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-215">https://issues.apache.org/jira/browse/TC-215</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment] 2019-11-19 03:09
duplicate of #1906

**Closed by mitchell852** 2019-11-19 03:09 UTC
Labels: SSL, Traffic Ops, enhancement, major, self_service
