### ISSUE TITLE
Altering Delivery Service with an Open Delivery Service Request Gives Error, but Updates Anyway

### ISSUE THREAD

**Issue by dsouza93** [apache/trafficcontrol#3717] opened 2019-07-10 17:04 UTC
When there is an open delivery service request for a delivery service, and a user attempts to change a value on the delivery service and "fulfill immediately", Traffic Portal displays an error that there is an active delivery service request open for said delivery service. The delivery service data is then updated anyway. I am not sure if this is intended behavior and is to serve as a warning or if it supposed to prevent updates, but thought I'd bring it up.

My specific use case was when there was a delivery service request in the "pending" status with the only action left was to "complete" the request. I then set the delivery service itself to "active"/"fulfill immediately" without completing the delivery service request. 

I am unsure if this will occur when other fields are altered or if it will occur when DS requests are in other states.

**Comment by anna-k-1** [comment] 2019-07-11 20:16
Is this a duplicate of: https://github.com/apache/trafficcontrol/issues/2595?

**Comment by rawlinp** [comment] 2019-07-12 18:44
It seems very related. The underlying bug _might_ be causing both issues. I'll take this description and add it to the other issue.

**Closed by rawlinp** 2019-07-12 18:44 UTC
Labels: Traffic Portal, bug
