### ISSUE TITLE
[TC-337] Inactive delivery services are added to remap.config

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#905] opened 2017-08-29 12:40 UTC
<p>Based on: <a href="https://github.com/Comcast/traffic_control/issues/1287" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1287</a></p>

<p>Some (maybe all) inactive delivery services (at least ANY_MAP) are added to remap.config. Inactive delivery services should not be in remap.config or any config for that matter.</p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-337">https://issues.apache.org/jira/browse/TC-337</a>

**Comment by smalenfant** [comment] 2017-08-30 18:13
@nir-sopher Based on the documentation, `When this is set to no Traffic Router will not serve DNS or HTTP responses for this delivery service.`

I've used this in the past to configured and test delivery service before pushing configuration down the Traffic Router. Like a pre-stage before enabling and CR-Config.

Should this be considered a feature or a bug?

**Comment by nir-sopher** [comment] 2017-08-31 05:05
@smalenfant  Note original defect by @elsloo  (Comcast/traffic_control#1287). I migrated it during the bug-scrub

As it is useful and somehow documented, I would consider it a feature with an "improvement" requirement to better define the "active" field, allowing it to have 3 modes (no deployment, caches-only, and full-deployment).
However, taking "tenancy" into account, such fields should be in the hands of the CDN owner and not the DS owner. I.e. they should not be part of the DS table.

Furthermore, taking into account the "deployed versions" table defined for [DSCV ](https://docs.google.com/document/d/1Dfy-iYxR8CQzxXx8cnJ68hrN3kr3R2mFP2no_fDouHc/edit?usp=sharing) (Delivery Service Configuration Versioning), the "active" field can be removed from the DS table, and the DS should be deployed if the version exists in the "deployed versions" table. The "deployed versions" table can have a "deploy-mode" field with the values "full" and "caches-only" - to support the usecase Steve described.

Therefore, I would not change this behavior for now.
@elsloo - what do you think.

**Comment by elsloo** [comment] 2017-08-31 14:16
If we're building a more comprehensive solution that supersedes the original issue referenced above, I'm okay with ignoring this for the time being. I'm not sure that allowing inactive delivery services in remap.config was a conscious decision, so @smalenfant might be relying on something that was unintended behavior. The documentation merely describes what Traffic Router does, not whether the remap exists on the edge.

I discussed this quickly with @PSUdaemon and @knutsel and they both suggested that we might want to introduce states on delivery services, much like we have on servers. For example, we might want to have "disabled," "mapped," "mapped and routed," "routed," etc. I think this still holds when we think about DSCV @nir-sopher, as a particular version of a delivery service could be in one of those states.

**Comment by dneuman64** [comment] 2017-08-31 19:16
@elsloo are you ok with moving this to a future release so we can figure out the right solution?

**Comment by rawlinp** [comment] 2017-09-09 14:06
This is somewhat related to #1121. If inactive delivery services are _not_ added to remap.config, then ANY_MAP delivery services will have to move to active, at which point the TR treats them similarly to HTTP delivery services, which is invalid according to the docs.

**Comment by mitchell852** [comment] 2019-08-05 19:41
duplicate of #3746

**Closed by mitchell852** 2019-08-05 19:41 UTC
Labels: Traffic Ops, bug, major
