### ISSUE TITLE
Undocumented TrafficOps endpoints and fields

### ISSUE THREAD

**Issue by moltzaum** [apache/trafficcontrol#3443] opened 2019-03-28 01:07 UTC
At the time of creating this issue, all the following endpoints were undocumented.
I can update the tickbox to be checked for each endpoint that is updated. Note: This may not be a comprehensive list.

**specific fields**
- [ ] user does not document lastUpdated for POST
- [ ] regions does not document lastUpdated for POST

**whole endpoints**
- [ ] GET steering
- [ ] POST statuses
- [ ] POST type
- [ ] PUT type
- [ ] DELETE type
- [ ] POST roles
- [ ] PUT roles
- [ ] DELETE roles
- [ ] DELETE divisions
- [ ] DELETE regions
- [ ] GET/POST/PUT/DELETE deliveryservice_requests
    - Note: A POST method is documented for `deliveryservices/request` (implemented in perl)
    - I'm not sure whether or not this supposed to be a different endpoint.

Note: most cases where an id is used I mean a path parameter because it is understood, but there are exceptions like `roles`, where only query parameters are used.

____

**Other incomplete documentation**
- [ ] `deliveryservices/dnsseckeys/generate`
    There is no example request structure

**Comment by ocket8888** [comment] 2019-03-28 06:02
Related: #2726

**Comment by ocket8888** [comment] 2020-01-30 23:06
I think this is now more fully captured and is just a duplicate of #4290 . Hopefully that one will get resolved before a year goes by and it's out of date.

**Closed by ocket8888** 2020-01-30 23:06 UTC
Labels: Traffic Ops, documentation, tech debt
