### ISSUE TITLE
'Add Failover cacheGroup' option in Failover cacheGroup adds a blank fallback cachegroup

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#3731] opened 2019-07-16 20:26 UTC
Version: 3.0.0-10156.528dd745.el7 (daily build)
Topology->cachegroups
Field:
 Failover Cache Groups: option 'Add Failover cacheGroup'
choose the option 'Add Failover cacheGroup'
adds a blank cachegroup fallback entry
On update, error message is displayed.  
Refer to the screen shots

if  'Add Failover cacheGroup' is used as a label -> it should not be displayed as option
if ' 'Add Failover cacheGroup' is expected to take to new cache group creation page -> it should get redirected appropriately.

<img width="1132" alt="Screen Shot 2019-07-16 at 1 34 04 PM" src="https://user-images.githubusercontent.com/26607771/61327019-42142580-a7d5-11e9-8ee2-70f6ba4c7ca1.png">

<img width="1133" alt="Screen Shot 2019-07-16 at 1 34 10 PM" src="https://user-images.githubusercontent.com/26607771/61327006-3b85ae00-a7d5-11e9-9b5a-24c2ea4adba3.png">
<img width="1184" alt="Screen Shot 2019-07-16 at 1 34 54 PM" src="https://user-images.githubusercontent.com/26607771/61327232-a800ad00-a7d5-11e9-9b91-5cc18f87b747.png">

**Comment by mitchell852** [comment] 2019-07-16 20:30
duplicate of #3533

**Closed** 2019-07-16 20:39 UTC
Labels: Traffic Portal, bug
