### ISSUE TITLE
[TC-36] Split query string option from cache key / parent selection

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#960] opened 2017-08-29 12:44 UTC
<p>Currently, a single delivery service field in Traffic Ops controls both the cache key behavior, and the parent selection behavior. There are often use cases for combinations that don't currently exist, so the best option is likely to split it into different fields.</p>

Author: Mark Torluemke
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-36">https://issues.apache.org/jira/browse/TC-36</a>
Found Version: 1.8.0

**Comment by mitchell852** [comment] 2020-08-04 16:15
duplicate of #3393

**Closed by mitchell852** 2020-08-04 16:15 UTC
Labels: Traffic Ops, enhancement, major
