### ISSUE TITLE
Internal Server Error returned from GET 1.5/servers/{{ID}}/configfiles/ats

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4796] opened 2020-06-15 21:29 UTC
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Perform a /GET `1.5/servers/170/configfiles/ats`
ERROR: api.go:201: 2020-06-15T21:03:15.365421062Z: 96.118.18.172:35220 GetConfigMetaData getting server info: querying server info: sql: Scan error on column index 7, name "tcp_port": converting NULL to int is unsupported

## Expected / new behavior:

User should able to view Config Files of the Servers

**Comment by ocket8888** [comment] 2020-06-15 21:42
Getting configs from the API is close to being phased out, so this might not get fixed and the functionality could just be removed instead.

**Comment by ocket8888** [comment] 2020-06-15 22:11
actually, I take that back. The dsId issue has a different root cause.

**Comment by mitchell852** [comment] 2020-08-13 19:36
this works fine in TC 4.1 and this endpoint has been removed in TC 5.0 so closing this...

**Closed by mitchell852** 2020-08-13 19:36 UTC
Labels: Traffic Ops, minor, regression bug
