### ISSUE TITLE
t3c support systemd-less systems

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#6204] opened 2021-09-13 19:21 UTC
## This Feature Request affects these Traffic Control components:
- Traffic Control Cache Config (T3C, formerly ORT)

## Description
t3c is currently incapable  of running successfully on systems that don't have `/usr/sbin/service` (which means even systems that DO have systemd, but are simply up-to-date are also unsupported). ATS itself can be started with `$TS_HOME/bin/trafficserver start` as an alternative to starting it with systemd, so commands can do that in the event that systemd is unavailable. Other daemons are harder to generally support, and should probably be skipped with a warning - or maybe require a special command-line flag to do so.

You can currently pass `-a`/`--service-action` set to `none` to disable _all_ restarts and reloads, but  as I mentioned above, trafficserver can still be manipulated without systemd.

**Comment by zrhoffman** [comment] 2023-08-02 23:10
Duplicate of #5829

**Closed by zrhoffman** 2023-08-02 23:10 UTC
Labels: new feature, low impact, cache-config, low difficulty
