### ISSUE TITLE
[TC-312] Hosts in PRE_PROD status with updates queued will prevent children from updating

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1006] opened 2017-08-29 12:47 UTC
<p>Children of hosts set to PRE_PROD will exit syncds because their parents still need an update. PRE_PROD should be ignored since they may not have the capability or the software needed to run syncds.</p>

<p>from <a href="https://github.com/Comcast/traffic_control/issues/1517" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1517</a></p>

Author: Dan Kirkwood
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-312">https://issues.apache.org/jira/browse/TC-312</a>

**Comment by mitchell852** [comment] 2020-07-14 15:55
duplicate of #3687

**Closed by mitchell852** 2020-07-14 15:55 UTC
Labels: Traffic Ops, bug, minor
