### ISSUE TITLE
Remove weight parameter from CRConfig.json

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#3974] opened 2019-10-09 21:05 UTC
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [X] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Currently the weight parameter with a configfile of CRConfig.json is required of each ATS server profile.  Because this is associated with the CRConfig.json even though it's an ATS thing, it's added to the general section of the CRConfig.  This causes an unexpected, yet harmless change, in the TrafficPortal Diff when updating this parameter on a subset of caches.  At the end of the day, the other change to the hashCount of a particular server is what matters.

## Expected / new behavior:

I would like to see the weight parameter excluded from the general section of the CRConfig.

## Minimal reproduction of the problem with instructions:

Create 2 ATS profiles with different weights associated with the CRConfig.json config file.  Observe that only the "last" value is present in the CRConfig diff in addition to the hashCount.

**Comment by rawlinp** [comment] 2019-10-09 21:25
I believe the issue is in this query: https://github.com/apache/trafficcontrol/blob/8c9d7bb914763ef077c8caadc6eb4914216a845a/traffic_ops/traffic_ops_golang/crconfig/config.go#L93

Only profile parameters assigned to the `TR_PROFILE` for a CDN should be queried and added into the CRConfig's "config" section. Arbitrary parameters assigned to non-TR_PROFILEs with the configFile of CRConfig.json (e.g. in this case, ATS_PROFILEs), should not end up in the CRConfig's "config" section.

**Comment by mitchell852** [comment] 2021-03-09 17:06
> Only profile parameters assigned to the `TR_PROFILE` for a CDN should be queried and added into the CRConfig's "config" section.

@rawlinp @jhg03a so this is a bug rather than an improvement?

**Comment by mitchell852** [comment] 2021-03-09 17:24
> It's harmless, so I'd be hesitant to call it a bug really. It just causes an unused option to show up in the crconfig.

tech debt then?

**Closed** 2022-10-13 18:27 UTC
Labels: Traffic Ops, crconfig-snapshot, low impact, tech debt
