### ISSUE TITLE
Remove DCZF cachegroup localization method from TP UI since it doesn't apply

### ISSUE THREAD

**Issue by 4701410** [apache/trafficcontrol#3247] opened 2019-01-21 20:20 UTC
It shouldn't hurt anything to have DCZF checked by default. The default behavior is to allow all localization methods for a given cachegroup. Unfortunately, due to "Deep Cachegroups" not being "real" cachegroups (i.e. they're defined only in the DCZF as opposed to in Traffic Ops), you can't really disable deep routing to a deep cachegroup. But by definition a deep cachegroup should always be enabled for deep-routing.

So maybe what we really need to do here is just remove the checkbox for DCZF from TP altogether since it doesn't really apply.

_Originally posted by @rawlinp in https://github.com/apache/trafficcontrol/issues/3067#issuecomment-443343049_

**Comment by rawlinp** [comment] 2019-01-22 17:14
@47014106 would you like to work on this one?

**Comment by mitchell852** [comment] 2019-12-05 15:13
closing as it is a duplicate of #3067

**Closed by mitchell852** 2019-12-05 15:13 UTC
Labels: Traffic Portal, enhancement
