### ISSUE TITLE
API "api/1.3/servers" doesn't work correctly

### ISSUE THREAD

**Issue by Shihta** [apache/trafficcontrol#3451] opened 2019-04-01 02:28 UTC
After CIAB started up, I want create a server via API `api/1.3/servers` so I use `to-post`;

1. enter enroller and then execute `. /to-access.sh`
2. execute `to-post "api/1.3/servers" edge-ecache-0.json`, it returns success

the content of `edge-ecache-0.json`:
```
{
  "hostName": "edge-ecache-0",
  "domainName": "infra.ciab.test",
  "cachegroup": "QCT_CG_Edge_Remote_0",
  "interfaceName": "eth0",
  "ipAddress": "172.24.0.3",
  "ipNetmask": "255.255.0.0",
  "ipGateway": "172.24.0.1",
  "ip6Address": "",
  "ip6Gateway": "",
  "interfaceMtu": 1500,
  "type": "EDGE",
  "physLocation": "Apachecon North America 2018",
  "profile": "QCT_EDGE_TIER_CACHE",
  "cdnName": "QCT-CDN",
  "updPending": false,
  "status": "REPORTED",
  "tcpPort": 80,
  "httpsPort": 443
}
```

the response:
```
{
  "alerts": [
    {
      "text": "server was created.",
      "level": "success"
    }
  ],
  "response": {
    "cachegroup": "QCT_CG_Edge_Remote_0",
    "cachegroupId": 8,
    "cdnId": 1,
    "cdnName": "QCT-CDN",
    "domainName": "infra.ciab.test",
    "guid": "",
    "hostName": "edge-ecache-0",
    "httpsPort": 443,
    "id": 19,
    "iloIpAddress": "",
    "iloIpGateway": "",
    "iloIpNetmask": "",
    "iloPassword": "",
    "iloUsername": "",
    "interfaceMtu": 1500,
    "interfaceName": "eth0",
    "ip6Address": null,
    "ip6Gateway": "",
    "ipAddress": "172.24.0.3",
    "ipGateway": "172.24.0.1",
    "ipNetmask": "255.255.0.0",
    "lastUpdated": "2019-04-01 02:19:01+00",
    "mgmtIpAddress": "",
    "mgmtIpGateway": "",
    "mgmtIpNetmask": "",
    "offlineReason": "",
    "physLocation": "Apachecon North America 2018",
    "physLocationId": 1,
    "profile": "QCT_EDGE_TIER_CACHE",
    "profileDesc": "",
    "profileId": 3,
    "rack": "",
    "revalPending": false,
    "routerHostName": "",
    "routerPortName": "",
    "status": "REPORTED",
    "statusId": 2,
    "tcpPort": 80,
    "type": "EDGE",
    "typeId": 19,
    "updPending": false,
    "xmppId": "trafficops-perl",
    "xmppPasswd": ""
  }
}
```

however, the data that actually exists in the system is:
```
docker-compose exec trafficops /bin/bash -c "source /to-access.sh && to-get 'api/1.4/servers?hostName=edge-ecache-0' | jq '.response[]'"

{
  "cachegroup": "CDN_in_a_Box_Edge",
  "cachegroupId": 8,
  "cdnId": 1,
  "cdnName": "ALL",
  "domainName": "infra.ciab.test",
  "guid": null,
  "hostName": "edge-ecache-0",
  "httpsPort": 443,
  "id": 19,
  "iloIpAddress": "",
  "iloIpGateway": "",
  "iloIpNetmask": "",
  "iloPassword": "",
  "iloUsername": "",
  "interfaceMtu": 1500,
  "interfaceName": "eth0",
  "ip6Address": null,
  "ip6Gateway": "",
  "ipAddress": "172.24.0.3",
  "ipGateway": "172.24.0.1",
  "ipNetmask": "255.255.0.0",
  "lastUpdated": "2019-04-01 02:19:01+00",
  "mgmtIpAddress": "",
  "mgmtIpGateway": "",
  "mgmtIpNetmask": "",
  "offlineReason": "",
  "physLocation": "Apachecon North America 2018",
  "physLocationId": 1,
  "profile": "TRAFFIC_OPS",
  "profileDesc": "Traffic Ops profile",
  "profileId": 3,
  "rack": "",
  "revalPending": false,
  "routerHostName": "",
  "routerPortName": "",
  "status": "ONLINE",
  "statusId": 2,
  "tcpPort": 80,
  "type": "TRAFFIC_OPS",
  "typeId": 19,
  "updPending": false,
  "xmppId": "trafficops-perl",
  "xmppPasswd": ""
}
```

as the response, you can see that the `cdnName`, `profile`, `type`, ... are different to the original request

**Comment by ocket8888** [comment] 2019-04-01 13:19
This is a known issue. Your request specified a `cdnName` but not a `cdnId`, a `profile` but not a `profileId`, and a `type` but not a `typeId`. None of the `{{x}}Name` fields have any effect on a request except that it sets the corresponding field in the response. All these operations must be done by ID, not name.

As to why it got those as defaults, I'm not sure.

**Comment by ocket8888** [comment] 2019-04-01 13:22
Also, that xmppId  is strange

**Comment by mitchell852** [comment] 2019-04-02 16:55
yeah, as @ocket8888 pointed out, i think the bug here is that the call to POST api/1.3/servers should have returned a 400 and never created the server because you did not provide 3 required fields (cdnId, typeId and profileId).

**Comment by moltzaum** [comment] 2019-04-04 14:51
It may be possible the required fields did not work because a past instance of the object retained those fields: https://github.com/apache/trafficcontrol/pull/3394

**Comment by rawlinp** [comment] 2019-07-16 20:06
This does sound like an issue caused by #3394, which should not be a problem anymore. Today, I would expect the API to return an error stating that certain fields that are required were missing from the request.

**Comment by mitchell852** [comment] 2019-09-18 20:17
closing. should be fixed but reopen if mistaken.

**Closed by mitchell852** 2019-09-18 20:17 UTC
Labels: Traffic Ops, bug
