### ISSUE TITLE
Fix Traffic Ops Golang CRUDer framework to query and return values for POST, PUT

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3341] opened 2019-02-20 15:42 UTC
The TO API defines POST and PUT to return the object, for most endpoints, but the CRUDer Framework doesn't, it just returns an empty success response.

I don't think it'll be that difficult to make the CRUDer Framework do this, by adding it to the `GenericCreate` and `GenericUpdate` funcs to expect an object to be returned from SQL and populate it, via the existing `sqlx` tags, and add that to each query via `RETURNING`.

This might ought to be tagged `bug`, it's a bug that the API is missing this from `1.x` where it existed before.

**Comment by rawlinp** [comment] 2019-08-19 19:49
This is a duplicate of https://github.com/apache/trafficcontrol/issues/2494

**Closed** 2019-08-19 19:50 UTC
Labels: tech debt
